Projet_dot_net_annonce/Controllers/UserannonceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Projet_dot_net_annonce.Data;
using Projet_dot_net_annonce.Models;
using Projet_dot_net_annonce.ServicesContracts;

namespace Projet_dot_net_annonce.Controllers
{
    public class UserannonceController : Controller
    {
        private readonly IAnnonceService _annonceService;

        private readonly AppDbContext _context;
        public UserannonceController(IAnnonceService annonceService, AppDbContext context)
        {
            _annonceService = annonceService;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Annonce> annonces = await _annonceService.GetAll();
            return View(annonces);
        }
        public async Task<IActionResult> Detail(int id)
        {
            Annonce annonce = await _annonceService.GetByIdAsync(id);
            return View(annonce);

        }

        public async Task<IActionResult> AffichageParCat(int CatId)
        {


            IEnumerable<Annonce> annonces = await _annonceService.GetAnnonceByCat(CatId);
            return View(annonces);
        }
        public IActionResult Create()
        {
            var cats = _context.Categories.ToList();
            ViewBag.Categories = cats.Select(cats =>
            new SelectListItem()
            {
                Text = cats.Name,
                Value = cats.Id.ToString()

            });
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create(Annonce annonce)
        {
            if (!ModelState.IsValid)
            {
                List<Categorie> cats = _context.Categories.ToList();
                //   var categories = await _categorieService.GetAll();

                ViewBag.Categories = cats.Select(cats =>
               new SelectListItem()
               {
                   Text = cats.Name,
                   Value = cats.Id.ToString()

               });

                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                //return View(annonce);
            }



            await _annonceService.Add(annonce);
            return RedirectToAction("Index");

        }
    }
}

Projet_dot_net_annonce/Views/Userannonce/Create.cshtml
@model Annonce
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout - Copier.cshtml";
}
<form method="post" asp-action="Create" >
    <div class="form-group">
        <label asp-for="Titre">Titre d'Annonce</label>
        <input asp-for="Titre" class="form-control" placeholder="Entrez le Titre d'Annonce" >
        <span asp-validation-for="Titre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Entrez la Description d'Annonce">
        <span asp-validation-for="Description" class=" text-danger"></span>
    </div>
      <div class="form-group">
        <label asp-for="email">email</label>
        <input asp-for="email" class="form-control" placeholder="Entrez Votre email">
        <span asp-validation-for="email" class=" text-danger"></span>
    </div>
      <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" class=" form-control" placeholder="Entrez Le lien d'Image'">
        <span asp-validation-for="Image" class=" text-danger"></span>
     </div>
    <div class="form-group">
        <label asp-for="Prix">Prix</label>
        <input asp-for="Prix" class=" form-control" placeholder="Entrez Le Prix d'Annonce'">
        <span asp-validation-for="Prix" class=" text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DateAnnonce">Date:</label>
        <input asp-for="DateAnnonce" type="date" class="form-control" id="dateInput"  data-date-format="dd/mm/yyyy" />
      </div>
    <div class="form-group">
        <label asp-for="CategorieId">Catégorie</label>
        <select asp-for="CategorieId" asp-items="@ViewBag.Categories" class="form-control">
            <option value="">-- Sélectionnez une catégorie --</option>
        </select>
        <span asp-validation-for="CategorieId" class="text-danger"></span>
    </div>
    <!-- <div class="form-group">
      <label asp-for="Categorie" >Categorie</label>
      <select asp-for="Categorie" asp-items="new SelectList(Model.Categorie.Name  , Model.Categorie.Id)"   class="form-control"> 
        <select asp-for="Categorie.Name"  class="form-control">
          <option>__select__</option>
        </select>
        </div> -->
   
 

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Projet_dot_net_annonce/Views/Userannonce/Detail.cshtml
@model Annonce
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

    Layout = "_Layout - Copier.cshtml";
}
<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        Page Heading
        <small>Secondary Text</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid" src= "@Model.Image" alt="">
        </div>

        <div class="col-md-4">
            <h3 class="my-3">@Model.Titre</h3>
            <p>@Model.Description</p>
            <h3 class="my-3">Les Details d'annonce</h3>
            <ul>
                <li>@Model.DateAnnonce</li>
                <li>@Model.Categorie.Name</li>
                
            </ul>
        </div>

    </div>
 
    <!-- /.row -->

</div>
<!-- /.container -->

Projet_dot_net_annonce/Views/Userannonce/Index.cshtml
@model IEnumerable<Annonce>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
    
*@
@{
    Layout = "_Layout - Copier.cshtml";
}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
       
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            @foreach (var item in Model)
            {
                if (@item.Etat == true)
                {
                    <div class="col-md-4">
                        <div class="card mb-4  box-shadow">
                    <img class="card-img-top" src="@item.Image" width="100%" height="255" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Titre</p>
                            <p class="card-text">@item.Description</p>
                       
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a type="btn btn-success" asp-controller="Userannonce" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Detail</a>
                                 
                                </div>
                                <small class="text-body-secondary">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
                }


            }



        </div>
    </div>
</div>

Projet_dot_net_annonce/Views/Userannonce/_Layout - Copier.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projet_dot_net_annonce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projet_dot_net_annonce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a asp-controller="Userannonce" asp-action="Create" class="nav-link active" >
                                Creer annonce 
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Userannonce" asp-action="Index" class="nav-link active">
                                Liste des annonce 
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                       

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Projet_dot_net_annonce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>