Projet_dot_net_annonce/Models/Categorie.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Projet_dot_net_annonce.Models
{
    public class Categorie
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Annonce> ? Annonces { get; set; }

    }
}

Projet_dot_net_annonce/Controllers/AnnonceController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Projet_dot_net_annonce.Data;
using Projet_dot_net_annonce.Models;
using Projet_dot_net_annonce.Services;
using Projet_dot_net_annonce.ServicesContracts;
using static System.Net.Mime.MediaTypeNames;

namespace Projet_dot_net_annonce.Controllers
{
    public class AnnonceController : Controller
    {
        private readonly IAnnonceService _annonceService;

        private readonly AppDbContext _context;
        public AnnonceController(IAnnonceService annonceService, AppDbContext context)
        {
            _annonceService = annonceService;
            _context = context;

        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Annonce> annonces = await _annonceService.GetAll();
            return View(annonces);
        }
        public async Task<IActionResult> Annonces_non_publiées()
        {
            IEnumerable<Annonce> annonces = await _annonceService.GetAll();
            return View(annonces);
        }

       
        public async Task<IActionResult> Detail(int id)
        {
            Annonce annonce = await _annonceService.GetByIdAsync(id);
            return View(annonce);

        }
       
        public async Task<IActionResult> Publier(int id)
        {
            Annonce annonce = await _annonceService.GetByIdAsync(id);
            annonce.Etat = true;

            await _annonceService.Edite(annonce);
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> AffichageParCat(int CatId)
        {


            IEnumerable<Annonce> annonces = await _annonceService.GetAnnonceByCat(CatId);
            return View(annonces);
        }
        public  IActionResult Create()
        {
            var cats = _context.Categories.ToList();
            ViewBag.Categories = cats.Select(cats =>
            new SelectListItem()
            {
                Text = cats.Name,
                Value = cats.Id.ToString()

            });
            return View();

        }
        [HttpPost]
        public async  Task<IActionResult> Create(Annonce annonce)
        {
            if (!ModelState.IsValid)
            {
                List<Categorie> cats = _context.Categories.ToList();
                //   var categories = await _categorieService.GetAll();

                ViewBag.Categories =  cats.Select(cats =>
               new SelectListItem()
               {
                   Text = cats.Name,
                   Value = cats.Id.ToString()

               });

                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                //return View(annonce);
            }



            await _annonceService.Add(annonce);
            return   RedirectToAction("Index");

        }

        public async Task<IActionResult> Edit(int id)
        {
            var cats =  _context.Categories.ToList();
            ViewBag.Categories = cats.Select(cats =>
            new SelectListItem()
            {
                Text = cats.Name,
                Value = cats.Id.ToString()

            });
            var annonce = await _annonceService.GetByIdAsync(id);
            if (annonce == null) return View("Error");
            var newannonce = new Annonce
            {
                Titre = annonce.Titre,
                Description = annonce.Description,
                Etat = annonce.Etat,
                Image = annonce.Image,
                Prix = annonce.Prix,
                DateAnnonce = annonce.DateAnnonce,
                email = annonce.email,
                Categorie = annonce.Categorie



            };
            return View(newannonce);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Annonce annonce)
        {
            if (!ModelState.IsValid)
            {
                List<Categorie> cats =  _context.Categories.ToList();


                ViewBag.Categories = cats.Select(cats =>
               new SelectListItem()
               {
                   Text = cats.Name,
                   Value = cats.Id.ToString()

               });
                ModelState.AddModelError("", "Erreur de Modification d'Annonce");
                return View("Edit", annonce);
            }
            var newannonce = new Annonce
            {
                Id = id,
                Titre = annonce.Titre,
                Description = annonce.Description,
                Etat = annonce.Etat,
                Image = annonce.Image,
                Prix = annonce.Prix,
                DateAnnonce = annonce.DateAnnonce,
                email = annonce.email,
                CategorieId = annonce.CategorieId,
                Categorie = annonce.Categorie

            };

           await   _annonceService.Edite(newannonce);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delet(int id)
        {
            var annonce = await _annonceService.GetByIdAsync(id);
            _annonceService.Delete(annonce);
                
            return RedirectToAction("Index");

        }

    }
}

Projet_dot_net_annonce/Controllers/CategorieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet_dot_net_annonce.Models;
using Projet_dot_net_annonce.Services;
using Projet_dot_net_annonce.ServicesContracts;

namespace Projet_dot_net_annonce.Controllers
{
    public class CategorieController : Controller
    {
        private readonly ICategorieService _categorieService;
        public CategorieController(ICategorieService categorieService)
        {
            _categorieService = categorieService;

        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Categorie> categories = await _categorieService.GetAll();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Categorie categorie)

        {
            if (!ModelState.IsValid)
            {

                return View(categorie);
            }

            await _categorieService.Add(categorie);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Edit(int id)
        {

            var categorie = await _categorieService.GetByIdAsync(id);
            if (categorie == null) return View("Error");
            var newcategorie = new Categorie
            {

                Name = categorie.Name


            };
            return View(categorie);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Categorie categorie)
        {
            if ( !ModelState.IsValid)
            {
                ModelState.AddModelError("", "Erreur de Modification d'Annonce");
                return View("Edit", categorie);
            }
            var newcategorie = new Categorie
            {
                Id = id,
                Name = categorie.Name
            };
            _categorieService.Edite(newcategorie);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Delet(int id)
        {
            var categorie = await _categorieService.GetByIdAsync(id);
            _categorieService.Delete(categorie);
            return RedirectToAction("Index");

        }
    }
}

Projet_dot_net_annonce/Views/Categorie/Create.cshtml
@model Categorie
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout - Copier.cshtml";
}

<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Name">Nom de Categorie</label>
        <input asp-for ="Name"  class="form-control" placeholder="Entrez le nom de categorie">
        <span asp-validation-for="Name" class="text-danger"></span> 
    </div>
   
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Projet_dot_net_annonce/Views/Categorie/Edit.cshtml
@model Categorie
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout - Copier.cshtml";
}
<form method="post" asp-action="Edit">
    <div class="form-group">
        <label asp-for="Name">Nom de Categorie</label>
        <input asp-for ="Name"  class="form-control" placeholder="Entrez le nom de categorie">
        <span asp-validation-for="Name" class="text-danger"></span> 
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Projet_dot_net_annonce/Views/Categorie/Index.cshtml
@model IEnumerable<Categorie>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout - Copier.cshtml";
}

<table class="table table-striped">
    <thead>
        <tr>
            
            <th scope="col">Id</th>
            <th scope="col">Nom</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            
        
        <tr>
            <th scope="row">@item.Id</th>
            <td>@item.Name</td>
                <td> <a asp-controller="Categorie"  asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                 <a asp-controller="Categorie" asp-action="Delet" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">Supprimer</a></td>
            
        </tr>
        }
    </tbody>
</table>

Projet_dot_net_annonce/Views/Categorie/_Layout - Copier.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projet_dot_net_annonce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projet_dot_net_annonce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Ajouter</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Annonce" asp-action="Create">Annonce</a>
                                
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Categorie" asp-action="Create">Categorie</a>
                            </div>
                        </li>
                         <li class="nav-item dropdown">
                           <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Lister</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Annonce" asp-action="Index">Annonces</a>
                                <a class="dropdown-item" asp-controller="Annonce" asp-action="Annonces_non_publiées">Annonces non publiées</a>
                                <a class="dropdown-item" asp-controller="Accounts" asp-action="Index">Les Utilisateurs</a>
                                <div class="dropdown-divider" ></div>
                                <a class="dropdown-item" asp-controller="Categorie" asp-action="Index">Categories</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Projet_dot_net_annonce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>